version: '3.8'

services:
  # Redis Cache only
  redis:
    image: redis:7-alpine
    container_name: puzzle-redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: