# Tier 2: Infrastructure Services (Redis + SQL Server + MQTT)
# Purpose: Verify all infrastructure services work together
# Test: docker-compose -f docker-compose.tier2-infra.yml up
# Verify: All services healthy, ports accessible

version: '3.8'

services:
  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: puzzle-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - puzzle-network

  # SQL Server Database
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: puzzle-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "YourStrong@Passw0rd" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 20s
    networks:
      - puzzle-network

  # MQTT Broker
  mqtt:
    image: eclipse-mosquitto:2
    container_name: puzzle-mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./docker/mosquitto/config:/mosquitto/config:ro
      - mqtt-data:/mosquitto/data
      - mqtt-log:/mosquitto/log
    networks:
      - puzzle-network

networks:
  puzzle-network:
    driver: bridge

volumes:
  redis-data:
  sqlserver-data:
  mqtt-data:
  mqtt-log: