version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.minimal
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Redis=redis:6379
    depends_on:
      - redis
    networks:
      - puzzle-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - puzzle-network

networks:
  puzzle-network:
    driver: bridge