version: '3.8'

services:
  # Redis only for initial testing
  redis:
    image: redis:7-alpine
    container_name: puzzle-redis-test
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # API with in-memory database for testing
  api:
    build:
      context: .
      dockerfile: Dockerfile.minimal
    container_name: puzzle-api-test
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Redis=redis:6379,abortConnect=false
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__Microsoft.AspNetCore=Warning
    ports:
      - "5000:80"
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./src/CollaborativePuzzle.Api/wwwroot:/app/wwwroot:ro