apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: puzzle-platform

bases:
- ../../base

commonLabels:
  environment: production

patchesStrategicMerge:
- deployment-patch.yaml
- resource-patch.yaml

configMapGenerator:
- name: puzzle-api-config
  behavior: merge
  files:
  - appsettings.Production.json

images:
- name: puzzle-api
  newName: myregistry.azurecr.io/puzzle-api
  newTag: v1.0.0

replicas:
- name: puzzle-api
  count: 5
- name: puzzle-redis
  count: 3
- name: puzzle-mqtt
  count: 2