apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: puzzle-db
spec:
  template:
    spec:
      containers:
      - name: sqlserver
        resources:
          limits:
            memory: "4Gi"
            cpu: "4000m"
          requests:
            memory: "2Gi"
            cpu: "1000m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: puzzle-redis
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: redis
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
          requests:
            memory: "512Mi"
            cpu: "250m"