apiVersion: apps/v1
kind: Deployment
metadata:
  name: puzzle-api
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: api
        imagePullPolicy: Always
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL