apiVersion: v1
kind: ConfigMap
metadata:
  name: puzzle-api-config
  labels:
    app: puzzle-api
data:
  appsettings.Production.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning",
          "Microsoft.AspNetCore.SignalR": "Information",
          "Microsoft.AspNetCore.Http.Connections": "Information"
        }
      },
      "AllowedHosts": "*",
      "SignalR": {
        "EnableDetailedErrors": false,
        "KeepAliveInterval": "00:00:15",
        "ClientTimeoutInterval": "00:00:30",
        "HandshakeTimeout": "00:00:15",
        "MaximumReceiveMessageSize": 32768
      },
      "Redis": {
        "InstanceName": "PuzzlePlatform",
        "Database": 0,
        "DefaultExpiry": "01:00:00",
        "ConnectRetry": 3,
        "ConnectTimeout": 5000,
        "SyncTimeout": 5000,
        "AbortOnConnectFail": false
      },
      "RateLimiting": {
        "PermitLimit": 100,
        "Window": "00:01:00",
        "QueueProcessingOrder": "OldestFirst",
        "QueueLimit": 50
      },
      "Authentication": {
        "Jwt": {
          "Issuer": "https://puzzle-api.example.com",
          "Audience": "https://puzzle-api.example.com",
          "ExpirationMinutes": 60
        },
        "ApiKey": {
          "HeaderName": "X-API-Key",
          "CacheDuration": "00:05:00"
        }
      },
      "WebRTC": {
        "StunServers": [
          "stun:stun.l.google.com:19302",
          "stun:stun1.l.google.com:19302"
        ],
        "TurnServers": [
          {
            "Urls": "turn:turn.example.com:3478",
            "Username": "turnuser",
            "Credential": "turnpassword"
          }
        ]
      },
      "MQTT": {
        "BrokerAddress": "mqtt-broker",
        "BrokerPort": 1883,
        "ClientId": "puzzle-api",
        "Username": "",
        "Password": "",
        "UseTls": false
      }
    }