apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: puzzle-platform

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - secret.yaml
  - ingress.yaml
  - hpa.yaml
  - redis.yaml
  - postgres.yaml
  - mqtt.yaml

commonLabels:
  project: collaborative-puzzle
  environment: base

images:
  - name: puzzle-api
    newTag: latest