# This is a template. In production, use sealed-secrets or external secret operators
apiVersion: v1
kind: Secret
metadata:
  name: puzzle-secrets
  labels:
    app: puzzle-api
type: Opaque
stringData:
  # Replace with actual connection strings
  redis-connection-string: "redis-master:6379,abortConnect=false"
  database-connection-string: "Server=postgres-service;Database=CollaborativePuzzle;User Id=puzzleuser;Password=changeme;TrustServerCertificate=true;"
  jwt-secret: "your-256-bit-secret-key-for-jwt-token-generation"
  turn-credential: "turnpassword"