apiVersion: v1
kind: Secret
metadata:
  name: puzzle-secrets
  namespace: puzzle-platform
type: Opaque
stringData:
  SQL_PASSWORD: "YourStrong@Passw0rd"
  REDIS_PASSWORD: "redis-secret-password"
  TURN_SECRET: "turn-shared-secret"
  JWT_SECRET: "your-256-bit-secret-key-for-jwt-tokens"
  MQTT_PASSWORD: "mqtt-broker-password"
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: puzzle-platform
type: kubernetes.io/tls
data:
  # Placeholder - replace with actual certificates
  tls.crt: LS0tLS1CRUdJTi...
  tls.key: LS0tLS1CRUdJTi...