apiVersion: apps/v1
kind: Deployment
metadata:
  name: puzzle-api
spec:
  template:
    spec:
      containers:
      - name: api
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: SignalR__EnableDetailedErrors
          value: "true"
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "100m"