apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: puzzle-api-ingress
spec:
  rules:
  - host: puzzle-api-dev.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: puzzle-api
            port:
              number: 80
  tls:
  - hosts:
    - puzzle-api-dev.example.com
    secretName: puzzle-api-dev-tls