apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: puzzle-platform-dev

bases:
  - ../../base

commonLabels:
  environment: development

patchesStrategicMerge:
  - deployment-patch.yaml
  - ingress-patch.yaml

configMapGenerator:
  - name: puzzle-api-config
    behavior: merge
    files:
      - appsettings.Development.json

replicas:
  - name: puzzle-api
    count: 1
  - name: redis-master
    count: 1
  - name: postgres
    count: 1